---
title: "imdb_data_analysis"
output: html_document
date: "2026-01-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r error=FALSE, warning=FALSE}
install.packages("tidyverse")
install.packages("ggplot2")
install.packages("dplyr")
install.packages("scales")
library(tidyverse)
library(ggplot2)
library(dplyr)
library(scales)
```

```{r error=FALSE, warning=FALSE}
basics <- read_tsv("title.basics.tsv", na = "\\N", quote = "")
episode <- read_tsv("title.episode.tsv", na = "\\N", quote = "")
ratings <- read_tsv("title.ratings.tsv", na = "\\N", quote = "")
```

```{r error=FALSE, warning=FALSE}
episode_summary <- episode %>%
  distinct(parentTconst, seasonNumber, .keep_all = TRUE) %>%
  filter(!is.na(parentTconst)) %>%
  group_by(parentTconst) %>%
  summarise(
    total_seasons = n(),
    .groups = 'drop'
  ) 
```

```{r error=FALSE, warning=FALSE}
df_plot <- basics %>%
  filter(!is.na(endYear)) %>%  
  inner_join(ratings, by = "tconst") %>%
  inner_join(episode_summary, by = c("tconst" = "parentTconst")) %>%
  filter(startYear >= 2000, startYear <= 2020) %>%
  filter(endYear < 2023) %>%
  filter(numVotes > 35000) %>%
  filter(total_seasons <= 20) %>%
  distinct(tconst, .keep_all = TRUE)
```

```{r error=FALSE, warning=FALSE}
ggplot(df_plot, aes(x = total_seasons, y = averageRating, size = numVotes, fill = numVotes)) +
  geom_jitter(shape = 21, color = "black", alpha = 0.8, width = .2) +
  scale_size(range = c(1, 15), name = "Number of votes") +
  scale_fill_gradient(
    low = "black", 
    high = "darkred",
    name = "Number of votes",
    guide = "legend"
  ) +
  scale_x_continuous(breaks = 1:15, limits = c(1, 15)) +
  scale_y_continuous(limits = c(0, 10)) + 
  theme_minimal() +
  labs(
    title = "Relationship between IMDb rating and season count",
    subtitle = "Series with more than 35k ratings",
    x = "Number of seasons",
    y = "Rating",
    caption = "Each bubble represents a TV series" 
  ) +
  coord_cartesian(ylim = c(6,10)) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    panel.border = element_rect(colour = "black", fill = NA, size = 1),
    panel.grid.minor = element_blank(),
    legend.position = "right",
    axis.text = element_text(size = 14),
    plot.caption = element_text(hjust = 0, face = "italic", color = "gray40")
  ) +
  guides(
    size = guide_legend(),
    fill = guide_legend()
  )

ggsave("graph_1.png", width = 10, height = 6, dpi = 300)
```

```{r error=FALSE, warning=FALSE}
filtered_ids <- df_plot %>%
  filter(total_seasons >= 5, averageRating >= 9) %>%
  pull(tconst)
writeLines(paste(filtered_ids, collapse = ","), "imdb_ids.csv")
```